Code
Koro0/Groupomania_frontend pull request #1
Opened 2022-10-05 11:19 UTC by Koro0

2022-10-07 10:39 UTC, Raiyol requested changes

2022-10-07 10:39 UTC, Raiyol commented on src/components/Header/Navbar/Navbar.jsx
> +import 'primeflex/primeflex.css';
De mémoire, tu as pas besoin d'importer ça dans chaque fichier. Fait le juste dans ton App.jsx et ces classes css seront disponible sur toute l'app. Essai et si c'est le cas enlève tous les endroits où tu as fait ces imports (sauf dans le App.jsx).

Encore mieux serait de l'importer dans ton fichier css dans App.css à la place de le faire dans le js.

Example, ligne a ajouté dans ton App.css à la place du js:

`@import 'primeflex/primeflex.scss';`

2022-10-07 10:39 UTC, Raiyol commented on src/components/Header/index.jsx
> +  if (userID != null) { setDiseableHeader(!isLogIn) };
Pas comme ça que tu es supposé de faire en React, et console.log a enlevé.

Pour les opérations que tu veux faire à l'initialisation, tu peux utiliser le [hook useEffet](https://fr.reactjs.org/docs/hooks-effect.html) 

Exemple d'utilisation: [W3school](https://www.w3schools.com/react/react_useeffect.asp)

Dans ton cas ce serait un truc comme ça qui se lance une seule fois à l'initialisation:

```jsx
useEffect(() => {
  //Runs only on the first render
  const userId = JSON.parse(localStorage.userId);
  if (userId != null) { setDiseableHeader(!isLogIn) };
}, []);
``` 

On peut encore simplifier: 

```jsx
useEffect(() => {
  //Runs only on the first render
  if (!!JSON.parse(localStorage.userId)) { setDiseableHeader(!isLogIn) };
}, []);
``` 

[Explication du double exclamation](https://www.codingem.com/javascript-double-exclamation-operator/#:~:text=The%20double%20exclamation%20point%20converts,be%20in%20a%20boolean%20context.)

Aussi userId et pas userID 😉.

2022-10-07 10:39 UTC, Raiyol commented on src/components/Header/index.jsx
> +          <Dialog header="Login" visible={displayLogin} style={{ width: '50vw' }} onHide={() => setDisplayLogin(false)}>
Essai d'évité le style dans le jsx si c'est pas un truc dynamique qui dépend d'une variable.

Go mettre ca dans le fichier css, pareil en bas 😉.

2022-10-07 10:40 UTC, Raiyol commented
Tu peux utiliser le scss avec react aussi, tu as pas le droit où c'est juste que tu as pas pensé à le faire ? Car c'est dmg de pas l'utiliser alors que tu as fait un cours & projet dessus.

2022-10-17 08:47 UTC, Koro0 commented on src/components/Header/Navbar/Navbar.jsx
> +import 'primeflex/primeflex.css';
je vais faire ca

2022-10-17 08:55 UTC, Koro0 commented on src/components/Header/index.jsx
> +          <Dialog header="Login" visible={displayLogin} style={{ width: '50vw' }} onHide={() => setDisplayLogin(false)}>
juste le style?

2022-10-17 09:05 UTC, merged